# fly.toml app configuration file generated for protohacker-in-rust on 2025-10-22T12:01:51+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'protohacker-in-rust'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
